### ISSUE TITLE
Will this be a paper or a blog post?

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/data_versioning#1]

**Comment by richfitz** [comment]
Let's start with a blog post but if we think that it's going to be worthwhile going all in on a paper we can do that.

**Comment by wcornwell** [comment]
OK.  Let's get `phydr` submitted and then we can flesh this out...

**Comment by richfitz** [comment]
Yeah, hoping to look at it again today.

**Comment by wcornwell** [comment]
paper!
