### ISSUE TITLE
Figure: illustrates semantic versioning

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/data_versioning#10]
This fig should do two things, explain the numbers:

![](https://image.slidesharecdn.com/semver-150821195016-lva1-app6892/95/semantic-versioning-7-638.jpg?cb=1440189143)

And also show series of releases, e.g.

![](https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQqnWX712tmPORnS85mi_C9eIrTdV8hMJIqJZIRE1MFVCabKzR6JA)

**Comment by wcornwell** [comment]
I like the top one as a figure; bottom one is too git-y for a general audience?

**Comment by wcornwell** [comment]
not sure if this is #10 or #11 

![image](https://user-images.githubusercontent.com/5534161/27525062-f1ffd6d0-5a7d-11e7-99fe-db073d75080e.png)

**Comment by wcornwell** [comment]
updated version:

![image](https://user-images.githubusercontent.com/5534161/27528498-fff62f8a-5a93-11e7-831d-5e7af711143b.png)

**Comment by dfalster** [comment]
- Add DOIs - in box with versions (different colour?)
- Remove 1 and 3rd columns

**Comment by wcornwell** [comment]
add some text in "A lightweight, cheap and scalable workflow for versioned data" section

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/28449852-9d99ec04-6e26-11e7-8f71-f9df12267d35.png)

**Comment by dfalster** [comment]
Nice!

**Comment by wcornwell** [comment]
still need to add dois:

some discussion of versioned dois here:
https://blogs.openaire.eu/?p=2010

**Comment by wcornwell** [comment]
figshare disagrees: https://support.figshare.com/support/solutions/articles/6000079064-can-i-edit-or-delete-my-research-after-it-has-been-made-public-

hmmmm

**Comment by wcornwell** [comment]
from the zenodo people:

> Why don’t the DOIs have a version number suffix like “.v1”?
> 
> Including semantic information such as the version number in a DOI is bad practice, because this information may change over time, while DOIs must remain persistent and should not change.
> 
> Moveover, Zenodo DOI versioning is linear, which means that the Zenodo version number may in fact not be the real version number of the resource. Take for instance software, where it is common practice to have dot versions and make new releases in a non-linear order (e.g. first v1.0, then v1.1, then v2.0, then v1.2).
> 
> The versioning suffix is also not a functionality of the DOI system, i.e. adding .v2 to DOI will not resolve to version 2 of a resource for any DOI from any provider. Different providers also uses different patterns such as e.g. .v2, .2, /2.
> 
> Most importantly, version suffixes are not machine readable. A discovery system that understands DOIs, will not know that .v1 and .v2 of a DOI are in fact two versions of the same resource.
> 
> A better solution to this problem is to semantically link two DOIs in the metadata of a DOI. This ensures that discovery systems have a machine readable way to discover that two DOIs are versions of the same resource.
> 
> See also “Cool DOIs”, a blog post by Martin Fenner, DataCite Technical Director: https://doi.org/10.5438/55E5-T5C0
>

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/28450755-b11b3a52-6e2c-11e7-89cb-3567c879a486.png)

**Comment by cboettig** [comment]
Also check out http://blog.zenodo.org/2017/05/30/doi-versioning-launched/ , and more details at: http://help.zenodo.org/#versioning (which now I see you've already quoted above)

Recall that if you turn the Zenodo integration switch on (much like a travis switch), zenodo will automatically assign a (now versioned) DOI to each github release, which I think works super nicely with the `datastorr` package since there's no need for the user to do anything on Zenodo or GitHub or anything, adding a tag on `datastorr` would give you the DOI automatically.  

Zenodo has had this behavior for a while, but the versioning now means that (a) the DOIs are numbered sequentially, and (b) most importantly, if you go to one DOI you get notified about the DOIs of newer and older versions.  You also get a DOI that always points to the most recent version.  
It's this grouping and seamless automation to get the new DOIs is really key, and the semantic debate is more of a distraction one way or another.  (e.g. perfectly fine to have semantic-versioned github tags/releases that are archived on zenodo with it's sequential but not semantic DOIs).

**Comment by dfalster** [comment]
Interesting debate! Thanks for sharing links and thoughts @cboettig @wcornwell. The post on cool dois was super useful. I was taken by the argument that dois should not contain semantic information.

@wcornwell: in your graphic perhaps change the top line to "

Some points I mentioned to Will last week

- from a citation-metrics perspective, i imagine most data producers would prefer 30 citations to a single resource rather than 30 citations being sprinkled over multiple dois (for different dataset versions), because they want/need to say stuff like "This dataset has been used XXX times". The solutions by both Zenodo ("concept doi") and figure (versioned doi) both enable this in different ways.
- from a reproducibility perspective, citing the actual version used is of course preferable

One problem with using zenodo and datastorr is that it doesn't allow for build artefacts to be archived, only the "code" part of the GH repo. This means it doesn't always work for datastorr, for example in the [BAAD](https://github.com/dfalster/baad) the final complied dataset is not  under version control, but is instead built (like a binary) from its parts and uploaded to the GH release.  I could change this so that I include  the built artefact under version control as well. Or we recommend anyone using that type of workflow use another provider.

I imagine @richfitz would be against the built object under version control, as it's wasteful and counter to common practice. But I can see some argument in it, as you then be able to see the changes in the  commit history on the final dataset, as well as the raw "code". Thoughts?

**Comment by cboettig** [comment]
@dfalster great point on archiving of built objects, see  https://github.com/zenodo/zenodo/issues/1235
