### ISSUE TITLE
Figure: illustrates technology stack

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/data_versioning#11]
I am thinking something that shows where the different technologies exist

This one is too complex, but that type of thing:

![](https://s-media-cache-ak0.pinimg.com/736x/8b/b9/ee/8bb9eecbd19c8011140b5f64e986c02b.jpg)

**Comment by wcornwell** [comment]
this could be branching flow chart style? maybe? like a decision tree?

**Comment by mwpennell** [comment]
i'm totally uninspired right now regarding this figure. though i've spent some time thinking about what this could look like, nothing i've thought about provides any added value to the text. perhaps one of who have some good ideas but at the moment, i'm leaning towards cutting out this figure.

**Comment by wcornwell** [comment]
@dfalster will have a think...

**Comment by dfalster** [comment]
How's this? Feedback welcome.

**Comment by dfalster** [comment]
![technology 1](https://user-images.githubusercontent.com/3589590/28905772-288146c6-7856-11e7-99e6-0e0ec8fb74f1.png)

**Comment by wcornwell** [comment]
I guess hypothetically non-git using data contributors could submit via a web interface that automatically creates a pull request from the git repo?  Maybe worth a dotted arrow?  would be more work to set up, but could explain this in the caption?

Also Github is a "host" rather than an "interface"?

**Comment by wcornwell** [comment]
Also maybe the "git users" could be "authorized curators" or something like that, so that it's clear that someone is in charge of looking after the database quality, which is also a point we should make in the text somewhere
