### ISSUE TITLE
concept needs a proper name

### ISSUE THREAD

**Issue by mwpennell** [traitecoevo/data_versioning#12]
for the sake of marketing and communications, i think we should pick a consistent name for the concept we are discussing.

**lightweight versioned data** (or, LVD in the ms) could work but of course there are many alternatives

**Comment by wcornwell** [comment]
I think LVD is alright, or at least I can't think of anything better.  

No real alternatives to the "versioned data" part.

I guess a data user wouldn't care if the data system is "lightweight" or "heavyweight", but we're trying to convince normal researchers that they can set up a LVD system.  And "lightweight" distinguishes our set of things from the set of things that already exist.  I guess we want to say "easy-to-set-up-and-maintain" in one word, but I can't think of any adjectives that do say that.

**Comment by wcornwell** [comment]
alternative: easy versioned data

**Comment by wcornwell** [comment]
versioned data delivery
