### ISSUE TITLE
Re-write abstract to focus on data versioning

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/data_versioning#21]
Subsequently discuss medium versus large data

this arises from @richfitz comments in 384b57b282527bcfdf3cffaf2a3a51b58811d2ba

**Comment by wcornwell** [comment]
@mwpennell can you have a look at this when you have a chance?

**Comment by mwpennell** [comment]
i like the new (second) version. think it reads nicer and gets to the point of data versioning
