### ISSUE TITLE
authorship reorder

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/data_versioning#26]
I _really_ think that Daniel should go first (I thought I added comments on this in my edits but obviously didn't).  Daniel and Will have clearly done the most work and are still actively engaged in careers where authorship order matters!

**Comment by wcornwell** [comment]
i agree 👍

**Comment by dfalster** [comment]
Thanks all (Matt also emailed to say he agreed with Rich).  I appreciate the thought and won't object. But only if i can handle the submission to journal - I love that part !!!!!!!

**Comment by richfitz** [comment]
> But only if i can handle the submission to journal - I love that part !!!!!!!

Sicko :stuck_out_tongue_winking_eye:
