### ISSUE TITLE
missing references

### ISSUE THREAD

**Issue by mwpennell** [traitecoevo/data_versioning#29]
what should go here (to replace 'REFS')? https://github.com/traitecoevo/data_versioning/blob/master/ms.tex#L123

**Comment by wcornwell** [comment]
Hart et al?

Hart, Edmund M., Pauline Barmby, David LeBauer, François Michonneau, Sarah Mount, Patrick Mulrooney, Timothée Poisot, Kara H. Woo, Naupaka B. Zimmerman, and Jeffrey W. Hollister. "Ten simple rules for digital data storage." PLoS computational biology 12, no. 10 (2016): e1005097.

also:

Frommhold, Marvin, Rubén Navarro Piris, Natanael Arndt, Sebastian Tramp, Niklas Petersen, and Michael Martin. "Towards versioning of arbitrary RDF data." In Proceedings of the 12th International Conference on Semantic Systems, pp. 33-40. ACM, 2016.
