### ISSUE TITLE
Minimal set of information required

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/data_versioning#3]
- repo name: `wcornwell/taxonlookup`, `traitecoevo/baad.data`
- single file name: `plant_lookup.csv`, `baad_data.zip`
- hook to load into R: `read_csv`, baad's bespoke functions
- additional version hook? (not clear, used in baad)

**Comment by wcornwell** [comment]
yes I think that's it.  see readme for https://github.com/traitecoevo/versioned_data_template
