### ISSUE TITLE
Forks

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/data_versioning#4]
As pointed out by @cboettig, think about what happens with forked data.  Do forks get numbers?  What happens on a merge?  (technically, can gh forks handle releases?)

**Comment by wcornwell** [comment]
There probably are a lot of OK solutions, and I don't think we have to be too prescriptive about it all.

But, at least for earth systems models, any serious fork that's going to last a while gets a (semi-meaningful) name and its own semantic versioning trajectory.  (There is a popular fork of the LPJ earth system model to develop fire behavior called Spitfire.)  I think they sometimes merge a big fork back to the main branch with a major version jump...
